apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: autoscale-test
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      # Kubelet (cAdvisor container metrics)
      - job_name: 'kubelet'
        scheme: https
        tls_config:
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc.cluster.local:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
      # Kubelet / node / pod metrics
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']

      # Test Go App
      - job_name: 'test-go-app'
        static_configs:
          - targets: ['test-go-app.autoscale-test.svc.cluster.local:8080']

      # Prometheus
      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus.autoscale-test.svc.cluster.local:9090']

      # Istio (если включён)
      - job_name: 'istio-mesh'
        static_configs:
          - targets: ['istio-proxy-metrics.kube-system.svc.cluster.local:15090']
