apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: autoscale-test
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      # Kubelet / node / pod metrics
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
      - job_name: 'metrics-server'
        scheme: https
        tls_config:
          insecure_skip_verify: true
        static_configs:
          - targets: ['metrics-server.kube-system.svc.cluster.local:443']

      # Test Go App
      - job_name: 'test-go-app'
        static_configs:
          - targets: ['test-go-app.autoscale-test.svc.cluster.local:8080']

      # Prometheus
      - job_name: 'prometheus'
        static_configs:
          - targets: ['prometheus.autoscale-test.svc.cluster.local:9090']

      # Istio (если включён)
      - job_name: 'istio-mesh'
        static_configs:
          - targets: ['istio-proxy-metrics.kube-system.svc.cluster.local:15090']
