apiVersion: v1
kind: ConfigMap
metadata:
  name: scaler-config
  namespace: autoscale-test
data:
  config.yaml: |
    prometheus_url: "http://prometheus.autoscale-test.svc.cluster.local:9090"
    prometheus_interval: 5s
    analyzer_interval: 15s
    scaling_cooldown: 60s
